/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/room1_color.glb 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera, OrbitControls } from '@react-three/drei'
import { Bloom, SelectiveBloom, EffectComposer } from '@react-three/postprocessing'
import { MathUtils } from 'three'

export function Model(props) {
  const { nodes, materials } = useGLTF('/room1_color.glb')
  // const bloomRef = React.useRef()
  return (
    <>
      <ambientLight intensity={0.5} />
      <directionalLight
        name="Directional Light"
        castShadow
        intensity={0.7}
        shadow-mapSize-width={1024}
        shadow-mapSize-height={1024}
        shadow-camera-near={-10000}
        shadow-camera-far={100000}
        shadow-camera-left={-1000}
        shadow-camera-right={1000}
        shadow-camera-top={1000}
        shadow-camera-bottom={-1000}
        position={[-5.6938, 5.1588, 8.537]}
      />
      <PerspectiveCamera name="Camera" makeDefault fov={45}
        position={[-4,3,8]}
        rotation={[-2.49, -0.68, -2.7]}
      />
      <group {...props} dispose={null}>
        <group position={[0, 0.896, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[141.627, -115.135, -24.442]} rotation={[-1.577, 0, 1.623]} scale={[0.261, 0.281, 0.363]}>
            <mesh geometry={nodes.Cube.geometry} material={materials['pink.001']} position={[-77.919, 8.91, -72.182]} scale={[1.399, 1.246, 1.487]} />
            <mesh geometry={nodes.Cube_2.geometry} material={materials['white.002']} position={[-54.541, -2.238, -73.075]} scale={[1.399, 1.246, 1.487]} />
            <mesh geometry={nodes.Cube_3002.geometry} material={materials['white.003']} position={[-5.526, -2.246, -82.106]} rotation={[0, 0, -0.095]} scale={[0.833, 1.242, 1.677]} />
            <mesh geometry={nodes.Cube_3003.geometry} material={materials['green.002']} position={[-18.749, 10.898, -81.099]} rotation={[0, 0, -0.095]} scale={[0.833, 1.242, 1.677]} />
            <mesh geometry={nodes.Cube_4002.geometry} material={materials['white.001']} position={[45.083, -2.246, -77.648]} rotation={[-0.002, 0.263, -0.1]} scale={[0.831, 1.243, 1.488]} />
            <mesh geometry={nodes.Cube_4003.geometry} material={materials.pink} position={[32.609, 10.898, -73.381]} rotation={[-0.002, 0.263, -0.1]} scale={[0.831, 1.243, 1.488]} />
          </group>
          <group position={[-149.063, -81.357, 69.69]} scale={[0.379, 0.326, 0.423]}>
            <mesh geometry={nodes.bucket.geometry} material={materials.parts} position={[-0.848, -2.542, -75.024]} rotation={[0, 0, -Math.PI / 2]} scale={0.899} />
            <mesh geometry={nodes.contornbucket.geometry} material={materials.metal} position={[-0.848, -2.542, -75.024]} rotation={[0, 0, -Math.PI / 2]} scale={0.909} />
            <mesh geometry={nodes.handle.geometry} material={materials['metal 2']} position={[-2.518, -2.641, -114.708]} rotation={[Math.PI / 2, 0, -2.608]} scale={1.255} />
            <mesh geometry={nodes.minihandle.geometry} material={materials['metal.001']} position={[-12.723, -16.52, -123.311]} rotation={[2.515, -0.915, -2.13]} scale={1.856} />
            <mesh geometry={nodes.tap_l.geometry} material={materials['metal.001']} position={[-3.994, 70.073, -115.585]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={1.294} />
            <mesh geometry={nodes.tap_r.geometry} material={materials['metal.001']} position={[-3.994, -75.977, -115.657]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={1.286} />
          </group>
          <group position={[-49.814, -5.82, 71.161]} rotation={[3.141, 0, -Math.PI]} scale={[-0.436, -0.436, -1.554]}>
            <mesh geometry={nodes.Ellipse.geometry} material={materials['yellow.001']} position={[0, 0, 2.712]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.398, 0.609, 0.398]} />
            <mesh geometry={nodes.Ellipse_2.geometry} material={materials['Material.017']} position={[0, 0, -2.712]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.398, 0.609, 0.398]} />
          </group>
          <group position={[27.258, 6.742, 46.999]}>
            <mesh geometry={nodes.Cube_5003.geometry} material={materials['Material.011']} position={[-12.094, -13.383, 4.069]} rotation={[-1.448, 0.782, -0.087]} />
            <mesh geometry={nodes.Cube_6002.geometry} material={materials['Material.011']} position={[11.948, 10.659, 4.069]} rotation={[-1.744, 0.778, 0.122]} />
            <mesh geometry={nodes.Cube_7003.geometry} material={materials['Material.011']} position={[-12.851, 11.271, 4.069]} rotation={[-1.697, -0.787, -0.09]} />
            <mesh geometry={nodes.Cube_7004.geometry} material={materials['Material.011']} position={[11.335, -12.626, 4.069]} rotation={[-1.447, -0.788, 0.088]} />
            <mesh geometry={nodes.Cylinder_4001.geometry} material={materials['Material.012']} position={[0, 0, -28.261]} rotation={[0, 0, -Math.PI / 2]} />
          </group>
          <group position={[27.258, -74.786, 46.999]}>
            <mesh geometry={nodes.Cube_5002.geometry} material={materials['Material.011']} position={[-12.094, -13.383, 4.069]} rotation={[-1.448, 0.782, -0.087]} />
            <mesh geometry={nodes.Cube_6001.geometry} material={materials['Material.011']} position={[11.948, 10.659, 4.069]} rotation={[-1.744, 0.778, 0.122]} />
            <mesh geometry={nodes.Cube_7001.geometry} material={materials['Material.011']} position={[-12.851, 11.271, 4.069]} rotation={[-1.697, -0.787, -0.09]} />
            <mesh geometry={nodes.Cube_7002.geometry} material={materials['Material.011']} position={[11.335, -12.626, 4.069]} rotation={[-1.447, -0.788, 0.088]} />
            <mesh geometry={nodes.Cylinder_4.geometry} material={materials['Material.012']} position={[0, 0, -28.261]} rotation={[0, 0, -Math.PI / 2]} />
          </group>
          <group position={[158.278, -12.48, 4.532]} rotation={[0, 0, 2.182]} scale={[0.235, 0.235, 0.226]}>
            <mesh geometry={nodes.base.geometry} material={materials.brown} position={[0.45, 9.011, -5.777]} scale={0.474} />
            <mesh geometry={nodes.centralsupport.geometry} material={materials.brown} position={[0.167, 110.754, -364.668]} rotation={[1.012, 0, 0]} scale={[0.15, 0.15, 1.199]} />
            <mesh geometry={nodes.lamp.geometry} material={materials.white} position={[0.167, 117.331, -357.161]} rotation={[-Math.PI / 6, 0, 0]} scale={[0.629, 0.629, 0.467]} />
            <mesh geometry={nodes.lightbulb.geometry} material={materials.yellow} position={[0.167, 121.513, -349.888]} rotation={[Math.PI / 3, 0, 0]} scale={0.148} />
            <mesh geometry={nodes.tube.geometry} material={materials.brown} position={[0.167, -29.448, -66.034]} scale={[0.326, 0.326, 0.592]} />
          </group>
          <group position={[109.057, -147.637, 1.513]} rotation={[0, 0, -1.484]} scale={[0.146, 0.108, 0.259]}>
            <mesh geometry={nodes.Cube_3.geometry} material={materials['blue.001']} position={[41.521, -1.186, -31.276]} rotation={[-Math.PI / 2, 0.029, 0]} scale={[1.199, 0.842, 1.199]} />
            <mesh geometry={nodes.Cube_4.geometry} material={materials['blue-dark']} position={[29.028, 0.013, -31.661]} rotation={[-Math.PI / 2, 0.029, 0]} scale={[1.199, 0.842, 1.199]} />
          </group>
          <group position={[135.728, 124.231, 65.394]} scale={[0.573, 0.573, 0.44]}>
            <group position={[1.361, -2.814, -140.596]} scale={0.68}>
              <mesh geometry={nodes.Cube_3001.geometry} material={materials['Material.004']} position={[13.847, 0, -55.823]} rotation={[0, 0.047, 0]} scale={1.521} />
              <mesh geometry={nodes.Cube_4001.geometry} material={materials['green.001']} position={[10.3, 1.82, -22.668]} rotation={[-0.053, -0.125, -0.007]} scale={1.521} />
              <mesh geometry={nodes.Cube_5.geometry} material={materials['green.001']} position={[-11.804, 4.971, 29.556]} rotation={[0, 0.436, -Math.PI]} scale={1.521} />
            </group>
            <mesh geometry={nodes.vase.geometry} material={materials['blue.003']} position={[1.559, -0.189, -19.527]} rotation={[-Math.PI / 2, 0, 0]} scale={1.034} />
          </group>
          <group position={[118.325, 62.837, 69.218]} scale={[0.344, 0.331, 0.399]}>
            <mesh geometry={nodes.Cylinder.geometry} material={materials.blue} position={[-0.962, -2.716, -55.486]} />
            <mesh geometry={nodes.Cylinder_2.geometry} material={materials.green} position={[-2.931, 3.721, -134.73]} />
            <mesh geometry={nodes.Cylinder_3.geometry} material={materials.green} position={[29.751, 9.976, -214.401]} rotation={[0.079, 0.037, 0.435]} />
          </group>
          <group position={[147.263, -93.678, -7.598]} rotation={[0, 0, -Math.PI]} scale={[-0.188, -0.188, -0.32]}>
            <group position={[-221.893, 42.415, -25.819]} rotation={[-Math.PI / 2, -0.12, 0]} scale={0.613}>
              <mesh geometry={nodes.Object_10.geometry} material={materials['Material.002']} position={[227.88, 0, 0]} />
              <mesh geometry={nodes.Object_11.geometry} material={materials['Material.002']} position={[303.84, 0, 0]} />
              <mesh geometry={nodes.Object_12.geometry} material={materials['Material.002']} position={[379.8, 0, 0]} />
              <mesh geometry={nodes.Object_13.geometry} material={materials['Material.002']} position={[455.76, 0, 0]} />
              <mesh geometry={nodes.Object_14.geometry} material={materials['Material.002']} position={[531.72, 0, 0]} />
              <mesh geometry={nodes.Object_15.geometry} material={materials['Material.002']} position={[607.68, 0, 0]} />
              <mesh geometry={nodes.Object_16.geometry} material={materials['Material.002']} position={[683.64, 0, 0]} />
              <mesh geometry={nodes.Object_7.geometry} material={materials['Material.002']} />
              <mesh geometry={nodes.Object_8.geometry} material={materials['Material.002']} position={[75.96, 0, 0]} />
              <mesh geometry={nodes.Object_9.geometry} material={materials['Material.002']} position={[151.92, 0, 0]} />
            </group>
            <mesh geometry={nodes.Rectangle_12.geometry} material={materials['Material.003']} position={[-16.011, 88.605, -9.612]} rotation={[-Math.PI / 2, -0.12, 0]} scale={0.613} />
            <mesh geometry={nodes.Rectangle_24.geometry} material={materials['Material.002']} position={[-221.893, 42.415, -25.819]} rotation={[-Math.PI / 2, -0.12, 0]} scale={0.613} />
            <mesh geometry={nodes.triangular_ruler.geometry} material={materials['blue.002']} position={[70.931, -40.371, -31.186]} rotation={[0, 0, 0.76]} scale={0.597} />
          </group>
          <group position={[100.318, -23.955, -23.772]} scale={[0.197, 0.177, 0.126]}>
            <group position={[0.066, -1.075, -221.022]}>
              <mesh geometry={nodes.cap001.geometry} material={materials['cap.001']} position={[0, 0, 8.813]} rotation={[0, 0, -0.464]} scale={[1.521, 1.521, 0.171]} />
              <mesh geometry={nodes.topcap.geometry} material={materials.cap} position={[0.104, -0.428, -9.308]} rotation={[-Math.PI, 0, 0.471]} scale={[8.942, 8.942, 1.215]} />
            </group>
            <group position={[0, 0, 215.436]} rotation={[0, 0, -0.405]} scale={2.021}>
              <mesh geometry={nodes.Mesh_9.geometry} material={materials.body} />
              <mesh geometry={nodes.Mesh_9_1.geometry} material={materials.body} />
              <mesh geometry={nodes.Mesh_9_2.geometry} material={materials.body} />
            </group>
            <mesh geometry={nodes.tag.geometry} material={materials.tag} position={[-0.423, -0.223, 25.887]} rotation={[0, 0, -0.464]} scale={[2.557, 2.561, 2.208]} />
          </group>
          <mesh geometry={nodes.Cube_10.geometry} material={materials['Material.009']} position={[-93.115, -134.987, -103.583]} rotation={[0.04, -0.013, -3.047]} />
          <mesh geometry={nodes.Cube_2001.geometry} material={materials['Material.014']} position={[115.876, -127.138, 43.82]} rotation={[0, 0, 1.208]} />
          <mesh geometry={nodes.Cube_3004.geometry} material={materials['Material.014']} position={[103.107, -41.823, 33.886]} rotation={[0, 0, 2.041]} />
          <mesh geometry={nodes.Cube_4004.geometry} material={materials['Material.014']} position={[37.09, -186.549, -149.118]} />
          <mesh geometry={nodes.Cube_5001.geometry} material={materials['Material.009']} position={[-117.62, -136.319, -15.132]} rotation={[1.507, 0.101, -2.944]} />
          <mesh geometry={nodes.Cube_6.geometry} material={materials['Material.009']} position={[-69.821, -130.945, -15.773]} rotation={[Math.PI / 2, 0.121, 2.967]} />
          <mesh geometry={nodes.Cube_7.geometry} material={materials['Material.009']} position={[-94.048, -123.325, -18.152]} rotation={[0, 0, -1.45]} />
          <mesh geometry={nodes.Cube_8.geometry} material={materials['Material.008']} position={[-93.374, -126.344, -75.589]} rotation={[-0.087, -0.01, -1.451]} />
          <mesh geometry={nodes.Cube_9.geometry} material={materials['Material.009']} position={[-91.213, -152.97, -3.777]} rotation={[1.682, 0.103, -3.136]} />
          <mesh geometry={nodes.Cylinder_2001.geometry} material={materials.table} position={[168.179, -169.87, 39.654]} rotation={[0, 0, -Math.PI]} scale={[1.014, 1.014, 0.592]} />
          <mesh geometry={nodes.Cylinder_3001.geometry} material={materials.table} position={[169.517, -8.714, 39.654]} rotation={[0, 0, -Math.PI]} scale={[1.014, 1.014, 0.592]} />
          <mesh geometry={nodes.Cylinder_3002.geometry} material={materials.table} position={[82.658, -8.714, 39.654]} rotation={[0, 0, Math.PI]} scale={[1.014, 1.014, 0.592]} />
          <mesh geometry={nodes.Cylinder001.geometry} material={materials.table} position={[81.32, -169.87, 39.654]} rotation={[0, 0, Math.PI]} scale={[1.014, 1.014, 0.592]} />
          <mesh geometry={nodes.Plane.geometry} material={materials['Material.014']} position={[37.566, -185.811, -146.714]} />
          <mesh geometry={nodes.Rectangle.geometry} material={materials.Walls} position={[10, -210, -102]} />
          <mesh geometry={nodes.Rectangle_10.geometry} material={materials['Material.014']} position={[180.755, -54.004, -117.476]} rotation={[0, 0, Math.PI / 2]} scale={[1.957, 1, 0.855]} />
          <mesh geometry={nodes.Rectangle_11.geometry} material={materials['Material.015']} position={[183.611, -79.004, -131.476]} rotation={[0, 0, Math.PI / 2]} scale={[1.957, 1, 0.855]} />
          <mesh geometry={nodes.Rectangle_12001.geometry} material={materials['Material.016']} position={[41.83, -182.026, -146]} />
          <mesh geometry={nodes.Rectangle_13.geometry} material={materials['Material.006']} position={[-109.044, -182, -141.447]} />
          <mesh geometry={nodes.Rectangle_2.geometry} material={materials.Walls} position={[210, -10, -102]} rotation={[0, 0, 1.572]} />
          <mesh geometry={nodes.Rectangle_3.geometry} material={materials.Walls} position={[10, -10, 68]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Rectangle_4.geometry} material={materials['table-mat']} position={[127.227, -89.5, 18.261]} rotation={[Math.PI / 2, 0, Math.PI]} />
          <mesh geometry={nodes.Rectangle_5.geometry} material={materials['Material.001']} position={[41.83, -184.361, -146]} />
          <mesh geometry={nodes.Rectangle_6.geometry} material={materials['Material.014']} position={[-110, -187, -140]} />
          <mesh geometry={nodes.Rectangle_7.geometry} material={materials['Material.014']} position={[185, -62.188, -119.5]} rotation={[0, 0, Math.PI / 2]} scale={[1.957, 1, 0.855]} />
          <mesh geometry={nodes.Rectangle_8.geometry} material={materials['Material.014']} position={[187, 116.898, -131]} rotation={[0, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Rectangle_9.geometry} material={materials['Material.007']} position={[186, 118.845, -134.534]} rotation={[0, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Sphere.geometry} material={materials['Material.013']} position={[9.446, -145, 48.357]} rotation={[Math.PI / 2, 0, Math.PI]} />
        </group>
      </group>
      <EffectComposer>
        <SelectiveBloom selection={nodes.lightbulb} intensity={1.5} luminanceThreshold={0.3} luminanceSmoothing={0.1} />
      </EffectComposer>
      <OrbitControls enableZoom minDistance={0.01} maxDistance={1000} />
    </>
  )
}

useGLTF.preload('/room1_color.glb')
